name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: created

jobs:
  build:  
    runs-on: [ubuntu-latest, macos-latest]

    steps:
    - name: get-cmake
      uses: lukka/get-cmake@v3.17.1
    - uses: actions/checkout@v2
    - name: run-cmake
      uses: lukka/run-cmake@v2.0
      with:
        cmakeBuildType: Release
