name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: created

jobs:
  build:  
    runs-on: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: mkdir build && cd build && cmake ..
    - name: make
      run: make
