name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: created

jobs:
  build:  
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, maxOS-latest]
    steps:
    - run: apt update -y; apt install -y libsqlite3-dev
    - name: get-cmake
      uses: lukka/get-cmake@v3.17.1
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
    - name: run-cmake
      uses: lukka/run-cmake@v2.0
      with:
        cmakeBuildType: Release
